version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

  fastapi:
    build:
      context: ./  # Change to your Next.js app directory

      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Add other environment variables as needed


volumes:
  redis_data:
